### ISSUE TITLE
Build error (at least for ghc 7.4.1)

### ISSUE THREAD

**Issue by letmaik** [choener/Nussinov78#1]
`cabal install Nussinov78` yields:

```
...
Registering ADPfusion-0.1.0.0...
Installing library in
...\cabal\ADPfusion-0.1.0.0\ghc-7.4.1
Registering ADPfusion-0.1.0.0...
Downloading Nussinov78-0.1.0.0...
Configuring Nussinov78-0.1.0.0...
Building Nussinov78-0.1.0.0...
Preprocessing library Nussinov78-0.1.0.0...
[1 of 1] Compiling BioInf.GAPlike   ( BioInf\GAPlike.hs, dist\build\BioInf\GAPlike.o )
...\cabal\ADPfusion-0.1.0.0\ghc-7.4.1\ADP\Fusion\GAPlike.hi
Declaration for R:StreamConstraint:.3:
  Iface type variable out of scope:  x
Cannot continue after interface file error
cabal: Error: some packages failed to install:
Nussinov78-0.1.0.0 failed during the building phase. The exception was:
ExitFailure 1
```

Do you know what the error could be?

**Comment by choener** [comment]
This is no bug. You need GHC 7.6 to be able to compile ADPfusion with ConstraintKinds.
I'll investigate if I can make inclusion of the ConstraintKinds stuff optional. You would, however, loose some functionality with GHC 7.4 an older.

I'll leave this open for now, a new version of ADPfusion should be online in a couple of days anyway.

**Comment by letmaik** [comment]
Ok, I'll try it with GHC 7.6. I usually use just the Haskell Platform (which has 7.4 for now).

**Comment by letmaik** [comment]
Hmm, I think I'll just wait for the next Haskell Platform or a new version of ADPfusion.

I got this after exchanging ghc:

```
cabal.exe: The following packages are likely to be broken by the reinstalls:
ghc-7.6.1
```

Oh well...

**Comment by letmaik** [comment]
I got it running now after upgrading to Ubuntu 13.04 as they package ghc 
7.6.2 there already. I didn't want to compile ghc from scratch.

After installing llvm through the package manager I got those two errors:
ghc: could not execute: opt-3.0
ghc: could not execute: llc-3.0

which I both fixed with some symlinks (I got llvm 3.2)...
ln -s /usr/bin/opt /usr/bin/opt-3.0
ln -s /usr/bin/llc /usr/bin/llc-3.0

Then it says "You are using a new version of LLVM that hasn't been 
tested yet!" but compiles.

The performance I get though is really dramatically low compared to 
Haskell-ADP. I guess either llvm 3.2 or ghc 7.6.2 is doing something 
wrong? Do you have an idea for that? Should I install llvm 3.0?

**Comment by choener** [comment]
I don't use Ubuntu, so I can't say if it is a problem there. How did you install Nussinov78? For whatever reason, the code was probably not fused. (FYI, I have ghc 7.6.2, llvm 3.2 installed, too)

A good idea is:
cabal update
cabal install cabal-dev
mkdir tmp
cd tmp
cabal-dev install Nussinov78

Then pipe, say, 100 sequences of length 100 - 1000 | ./cabal-dev/bin/Nussinov78 gaplike 1
so that program startup times don't skew your runtimes.

Btw. if you have ghc-core installed and know how to use it, copy the stuff below and to check the core.

#!/bin/bash
ghc-core -- -package-conf cabal-dev/packages-`ghc -V | awk '{print $NF}'`.conf \
  -Odph \
  -funbox-strict-fields \
  -funfolding-use-threshold100 \
  -funfolding-keeness-factor100 \
  $@

**Comment by letmaik** [comment]
Ok it works fine when I use it stand-alone. What I try is to use it 
directly as a library as part of some benchmarks with criterion. I 
noticed that the ghc-options in your Nussinov78.cabal are different for 
the library and the executable. Might that be the problem?

**Comment by choener** [comment]
What options do you use? You probably need "-O2". The others are llvm-specific but should be enabled as well. You need to set optimization levels high so that fusion happens properly.

Unfortunately, this also means to set some functions to INLINE.  Some of the vector + repa comments might help:
http://www.haskell.org/haskellwiki/Numeric_Haskell:_A_Repa_Tutorial

**Comment by letmaik** [comment]
Hmm, I think you misunderstood me. I use Nussinov78 by adding it to 
build-depends of my own project. Isn't Nussinov78 compiled separately 
as a library using the ghc-options in Nussinov78.cabal and not my own 
ones?

**Comment by choener** [comment]
Can you make your code available? It should work as you said, but only if you use the default wrapping function "nussinov78", as that one is set NOINLINE.

**Comment by letmaik** [comment]
Sure, it's at https://github.com/neothemachine/adp-multi
The benchmark executable is only compiled with the flag 
--flags=buildBenchmark and is called adp-multi-benchmarks. The 
benchmarks main() is at benchmarks/Benchmarks.hs.

**Comment by choener** [comment]
Hi,

I see the problem now. Use this line in Benchmarks.hs
bgroup "nussinov78 (ADPfusion)" (benchArray (fst . Nuss3.nussinov78) inputs)

The "fst . nussinov78" returns just the optimal score. In "snd . ", you get a list of /all/ co-optimal parses, of which there are really many ;-) And we are back to being really fast!

benchmarking nussinov78 (ADPfusion)/100
mean: 1.682468 ms, lb 1.664126 ms, ub 1.705257 ms, ci 0.950
std dev: 104.2774 us, lb 87.96967 us, ub 119.6883 us, ci 0.950

benchmarking nussinov78 (adp-multi)/100
collecting 100 samples, 1 iterations each, in estimated 37.50961 s
mean: 420.8677 ms, lb 411.4006 ms, ub 433.5635 ms, ci 0.950

**Comment by letmaik** [comment]
Ah, that looks better! :) Thanks for finding the problem!

**Comment by letmaik** [comment]
I'll close this now as the new Haskell Platform is coming soon anyway. No need for building a less-feature version or something.
