### ISSUE TITLE
Use different nussinov grammar

### ISSUE THREAD

**Issue by letmaik** [choener/Nussinov78#2]
If I see it correctly, you use the Durbin variant which is semantically ambiguous. Is there a reason for that? Why not stay with the unambiguous one (`S -> .S | (S)S | €`) so that you can implement a counting algebra?

**Comment by choener** [comment]
Well, the reason is that the Nussinov library is mostly a vehicle to observe fusion. I look at the generated Core language and check if everything is unboxed.

For that, the currently implemented variant is more useful:
`S -> S S` is the simplest way to observe non-terminals in action;
`S -> a S | S a` use different ways of `mapM` -ing stuff. We don't want a loop here, just a single case statement.
`S -> c S c` should, again, not need a loop. Also, we can automatically pull out some checks.

Some of these things will only become active with the next update to ADPfusion sometime this month (around the 27th actually ;-) and use smarter compile-time evaluation of the right-hand sides.

**Comment by choener** [comment]
Btw. I'm leaving this open and will provide the other version of the grammar as well.

**Comment by letmaik** [comment]
Want! :)

**Comment by choener** [comment]
never closed this; ADPfusion has both variants as examples.
